/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 m4.gltf 
Author: instagram1m_lal (https://sketchfab.com/1m_lal)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/m416-the-fool-310555d2bc2a4363922d1f45a786e9ea
Title: m416 the Fool
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Model(props) {

  const group = useRef();


  useFrame((state, delta)=>{
    group.current.rotation.y +=delta; 
 })



  const { nodes, materials } = useGLTF('/m4.gltf')
  return (
    <group ref={group} {...props} dispose={null} scale={200}>
      <group scale={0.01}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['mat0.004']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['mat0.005']} />
      </group>
    </group>
  )
}

useGLTF.preload('/m4.gltf')
